name: CD

on:
  release:
    types:
      - published

jobs:
  cd:
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-cd.yaml@v4
    secrets:
      # 发布到Halo应用商店所需的个人访问令牌
      halo-pat: ${{ secrets.HALO_PAT }}
    permissions:
      contents: write
    with:
      skip-node-setup: false
      ui-path: "."
      app-id: app-od18rwfb
